* **General**

  * :doc:`Code Review and Communication </communication>`

* **Code**

  * :doc:`Code Review </communication>`
  * :doc:`Patches </code/patches>`
  * :doc:`Security </code/security>`
  * :doc:`Testing </code/testing>`
  * :doc:`Coding Standards </code/standards>`
  * :doc:`Symfony </code/symfony>`
  * :doc:`Twig </code/twig>`
  * :doc:`Code Conventions </code/conventions>`
  * :doc:`Git </code/git>`

* **Documentation**

  * :doc:`Format </documentation/format>`
  * :doc:`Documentation Standards </documentation/standards>`
  * :doc:`License </documentation/license>`
