* **Code**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`The Core Team </contributing/code/core_team>`
  * :doc:`Security </contributing/code/security>`
  * :doc:`Tests </contributing/code/tests>`
  * :doc:`Backwards Compatibility </contributing/code/bc>`
  * :doc:`Coding Standards</contributing/code/standards>`
  * :doc:`Code Conventions</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`

* **Documentation**

  * :doc:`Overview </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Documentation Standards </contributing/documentation/standards>`
  * :doc:`License </contributing/documentation/license>`
