* **Code**

  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Security </contributing/code/security>`
  * :doc:`Testing </contributing/code/testing>`
  * :doc:`Coding Standards</contributing/code/standards>`
  * :doc:`Symfony </contributing/code/symfony>`
  * :doc:`Twig </contributing/code/twig>`
  * :doc:`Code Conventions</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`

communication

* **Documentation**

  * :doc:`Overview </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Documentation Standards </contributing/documentation/standards>`
  * :doc:`License </contributing/documentation/license>`
